[package]
name = "ecdsa"
version = "0.1.0"
edition = "2021"

[dependencies]
ecc = { path = "../ecc", default-features = false }
num-bigint = { version = "0.4", features = ["rand"] }
num-integer = "0.1"
num-traits = "0.2"
rand = "0.8"
subtle = { version = "2.3", default-features = false }
libsecp256k1 = "0.7"
hex = "0.4"
dotenv = "0.15"
wasm-bindgen = "0.2.84"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
getrandom = { version = "0.2", features = ["js"] }
rand_core = { version = "0.6", default-features = false }

[features]
default = []
circuit-params = ["ecc/circuit-params"]

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false